### PR TITLE
Result exports bug fix

### PR DESCRIPTION
**Pull request by Hassan754**

### CODE REVIEW

**Review by hannesdiedrich — DISMISSED** [review]
LGTM

**Review by spyrostz — COMMENTED** [review]
Change looks good to me indeed, however it would be great to repeat the behavior in the self.max_trade_price (use None value if there is no trades in the market) for consistency.

**Review by spyrostz — APPROVED** [review]
LGTM, thanks for the extra fix on the min/max_offer_price!

**Review by hannesdiedrich — APPROVED** [review]
LGTM

**Pull request merged**
