### PR TITLE
Urllib version sync

### PR DESCRIPTION
**Pull request by Hassan754**
Sync urllib version with that of d3a-api-client/ d3a-interface

### CODE REVIEW

**Comment by hannesdiedrich** [comment]
Do you mind upgrading pyaml and py to (as dependabot suggested)? Thanks!

**Comment by Hassan754** [comment]
> Do you mind upgrading pyaml and py to (as dependabot suggested)? Thanks!

I upgraded pyaml but left py as it will require extra PR in the d3a-interface and this PR is a bit urgent

**Comment by Hassan754** [comment]
> In d3a we use `pip-tools` to manage dependencies, so this change would be undone next time we run `pip-compile` (or `fab compile`). I would suggest either upgrading both `d3a-interface` and `d3a` requirements (if they end up to the same version) or pinning these requirements in `base.in` (not `base.txt`).

It looks the version was already pinned, I updated it

**Review by fievelk — APPROVED** [review]

**Review by faizan2590 — APPROVED** [review]
LGTM

**Pull request merged**
