### PR TITLE
D3ASIM-3351: deprecate market_stats

### PR DESCRIPTION
**Pull request by fievelk**
Deprecate features related to `market_stats` (not for DSOs).

## Related PRs

- https://github.com/gridsingularity/d3a-api-client/pull/119
- https://github.com/gridsingularity/d3a-web/pull/1274

### CODE REVIEW

**Review by hannesdiedrich — APPROVED** [review]
LGTM

**Review by Hassan754 — APPROVED** [review]
LGTM

**Review by faizan2590 — APPROVED** [review]
LGTM

**Comment by hannesdiedrich** [comment]
@fievelk This can be pushed, right=

**Comment by fievelk** [comment]
> @fievelk This can be pushed, right=

Yes, I thought you wanted to wait for #1112 to be pushed first. If that's not important, I'll go on and merge this.

**Pull request merged**
